- name : run consul
  sudo : yes
  when : consul is defined and consul.client and consul.join_ip is defined
  docker : 
    hostname : "{{consul.hostname}}"
    restart_policy : always
    name : consul
    log_driver : syslog
    image : progrium/consul
    state : reloaded
    command : -advertise {{consul.public_ip}} -bootstrap-expect 1 -join {{consul.join_ip}}
    ports :
    - "{{consul.public_ip}}:8300:8300"
    - "{{consul.public_ip}}:8301:8301"
    - "{{consul.public_ip}}:8302:8302"
    - "{{consul.public_ip}}:8400:8400"
    - "{{consul.public_ip}}:8500:8500"
    - "{{consul.public_ip}}:8301:8301/udp"
    - "{{consul.public_ip}}:8302:8302/udp"
    - "{{consul.bridge_ip}}:53:53"
    - "{{consul.bridge_ip}}:53:53/udp"

- name : run consul
  sudo : yes
  when : consul is defined and consul.join_ip is defined and (consul.client is undefined or not consul.client)
  docker : 
    hostname : "{{consul.hostname}}"
    log_driver : syslog
    restart_policy : always
    name : consul
    image : progrium/consul
    state : reloaded
    command : -server -advertise {{consul.public_ip}} -bootstrap-expect 1 -join {{consul.join_ip}}
    ports :
    - "{{consul.public_ip}}:8300:8300"
    - "{{consul.public_ip}}:8301:8301"
    - "{{consul.public_ip}}:8302:8302"
    - "{{consul.public_ip}}:8400:8400"
    - "{{consul.public_ip}}:8500:8500"
    - "{{consul.public_ip}}:8301:8301/udp"
    - "{{consul.public_ip}}:8302:8302/udp"
    - "{{consul.bridge_ip}}:53:53"
    - "{{consul.bridge_ip}}:53:53/udp"

- name : run consul
  sudo : yes
  when : consul is defined and consul.join_ip is undefined
  docker : 
    hostname : "{{consul.hostname}}"
    log_driver : syslog
    restart_policy : always
    name : consul
    image : progrium/consul
    state : reloaded
    command : -server -advertise {{consul.public_ip}} -bootstrap-expect 1
    ports :
    - "{{consul.public_ip}}:8300:8300"
    - "{{consul.public_ip}}:8301:8301"
    - "{{consul.public_ip}}:8302:8302"
    - "{{consul.public_ip}}:8400:8400"
    - "{{consul.public_ip}}:8500:8500"
    - "{{consul.public_ip}}:8301:8301/udp"
    - "{{consul.public_ip}}:8302:8302/udp"
    - "{{consul.bridge_ip}}:53:53"
    - "{{consul.bridge_ip}}:53:53/udp"

- name : run registrator
  sudo : yes
  when : consul is defined and consul.registrator
  docker : 
    restart_policy : always
    log_driver : syslog
    name : registrator
    image : gliderlabs/registrator
    state : reloaded
    command : --ip {{consul.public_ip}} consul://{{consul.public_ip}}:8500
    net : host
    volumes:
    - /var/run/docker.sock:/tmp/docker.sock
