- name : start graphite
  sudo : yes
  docker : 
    name : graphite
    restart_policy : always
    image : hopsoft/graphite-statsd
    state : started
    log_driver : syslog
    ports : 
      - 81:80
      - 2003:2003
      - 8125:8125/udp
