- name : start graphite
  sudo : yes
  docker : 
    name : graphite
    restart_always : true
    image : hopsoft/graphite-statsd
    state : reloaded
    ports : 
      - 81:80
      - 2003:2003
      - 8125:8125/udp
